### ISSUE TITLE
Mobile Notifications 2.1.0 -> not showing the latest version

### ISSUE THREAD

**Issue by dcosmin-97** [Unity-Technologies/com.unity.mobile.notifications#228]
Hello!

Mobile Notifications 2.1.0 is not available yet in the package manager.
Is there a way to fix this other than installing manually the latest version?

Thank you!

![image](https://user-images.githubusercontent.com/66071707/193777275-5b9b8fcb-dabf-4c52-8cd4-0a19fb6623a1.png)

**Comment by Bruno-LKWD** [comment]
No one?! :(

**Comment by dcosmin-97** [comment]
It was solved few days ago.

**Comment by Bruno-LKWD** [comment]
> It was solved few days ago.

![image](https://user-images.githubusercontent.com/108861758/196378783-7ab454df-0448-41a7-a48b-58b90ade7760.png)

For me is still showing only 2.0.2 I had to manually install 2.1.0

Unity: 2020.3.34f1
